### ISSUE TITLE
Cannot import characters wearing the Biker Vest from the "CC3 Outfit and Accessory" pack.

### ISSUE THREAD

**Issue by jdavies** [soupday/cc3_blender_tools#53]
Steps to reproduce:

1. Open CC3
2. Open the "CC3 Outfit and Accessory" pack.
3. Add the "Biker Vest.ccCloth" to the  default  characxter in CC3.
4. Export the character as an iAvatar using the  default values (ie no LOD)
5. Open iClone 7.9
6. Import the iAvatar into iClone.
7. Select the character in iCLone and export as  FBX. I usually uncheck the "Embed Textures" and check "Delete Hidden Faces" You can select current frame or range. 
8. Open Blender 3.0.1 (I  dont think this  is  version specific to Blender)
9. Using the CC3 addon for Blender, import the character in FBX format.

The following error message appears in the Blender Info Log:

```
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\__init__.py", line 216, in execute
    if import_fbx.load(self, context, filepath=path, **keywords) == {'FINISHED'}:
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 2600, in load
    _(); del _
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 2599, in _
    fbx_item[1] = blen_read_geom(fbx_tmpl, fbx_obj, settings)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 1296, in blen_read_geom
    blen_read_geom_layer_uv(fbx_obj, mesh)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 1061, in blen_read_geom_layer_uv
    blen_read_geom_array_mapped_polyloop(
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 984, in blen_read_geom_array_mapped_polyloop
    blen_read_geom_array_setattr(blen_read_geom_array_gen_indextodirect(fbx_layer_index, stride),
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 840, in blen_read_geom_array_setattr
    _process(blen_data, blen_attr, fbx_data, xform, item_size, blen_idx, fbx_idx)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\io_scene_fbx\import_fbx.py", line 835, in _process
    setattr(blen_data[blen_idx], blen_attr, fbx_data[fbx_idx:fbx_idx + item_size])
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 2 items, not 0

location: <unknown location>:-1

```
**Note:** I have only found this to happen with the biker vest, not with any other assets in that pack. From the stack trace it could be  argued that this is not a  CC3 addon error, but an FBX import error. However, I encountered  this via the CC3 addon and it only happens  with this biker vest model.  I'm posting it here  in case you know  of a better place to post it.

Thanks, as always!

- Jeff

**Comment by soupday** [comment]
The UV map in that Biker Vest is completely broken and Blender won't have anything to do with it.

There are some sample characters wearing the vest that aren't broken, if you want a version that works in Blender, you can save the vest out in CC3 and re-use it.

**Comment by jdavies** [comment]
Sweet! Thanks for the tip!
