### ISSUE TITLE
FBX Character import from CC3 get error message (for every version above V1.2.1

### ISSUE THREAD

**Issue by evokra** [soupday/cc3_blender_tools#69]
As suggested by the title, an error message poped up upon importing the character to blender.
This issue **only appears with plugin version 1.2.2 - latest.**
![image](https://user-images.githubusercontent.com/96784532/165032316-f758f836-22a3-4600-858e-fa41daf921d2.png)
The import seems to be incomplete as all materials includes only diffuse and normal map. The custom node group that comes with earlier version import is also missing.
![image](https://user-images.githubusercontent.com/96784532/165032601-56ec8ca2-4c65-4876-a4d5-d77a2b30f6ab.png)
The detailed error message are as follows

Python: Traceback (most recent call last):
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\importer.py", line 814, in modal
    self.run_import(context)
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\importer.py", line 728, in run_import
    self.import_character(warn)
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\importer.py", line 619, in import_character
    self.imported_character = detect_character(self.filepath, type, imported, actions, json_data, warn)
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\importer.py", line 472, in detect_character
    chr_cache.add_object_cache(arm)
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\properties.py", line 1310, in add_object_cache
    cache.source_name = utils.strip_name(obj.name)
  File "C:\Users\Thomas ma\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\cc3_blender_tools-1_3_3\utils.py", line 512, in strip_name
    if name[-3:].isdigit() and name[-4] == ".":
IndexError: string index out of range

location: <unknown location>:-1

**Comment by evokra** [comment]
FYI this is unlikely an issue caused by ACES color space as it already appears before ACES installation.
